In [1]:
import numpy, pandas 
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans

from PIL import Image

In [2]:
img = Image.open("dogs.jpeg")

np_array = numpy.array(img)

flat_array = np_array.ravel()

new_array = flat_array.reshape(np_array.shape[0] * np_array.shape[1], np_array.shape[2])


In [3]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(new_array)

print("\nCluster centroids")
print(kmeans.cluster_centers_)


Cluster centroids
[[ 29.52342938  21.58259063  20.44042867]
 [251.54389765 247.64181736 243.03339546]
 [210.47150599 174.81721136 143.77204796]]


In [4]:
print("Elements of Each cluster ")
unique, counts = numpy.unique(kmeans.labels_, return_counts=True)
print(dict(zip(unique, counts)))

Elements of Each cluster 
{0: 18294, 1: 19824, 2: 12202}
