In [3]:
import numpy, pandas 
import matplotlib.pyplot as plt 

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from sklearn.decomposition import PCA

In [4]:
digits = load_digits()

images = digits.images.reshape(digits.images.shape[0], -1)

labels = digits.target

train_x, test_x, train_y, test_y = train_test_split(images, labels, random_state=10, test_size=0.20)

model_pca = PCA(n_components=10)

model_pca.fit(images)

model_pca.fit(train_x, train_y)

train_x = model_pca.transform(train_x)

test_x = model_pca.transform(test_x)

In [5]:

new_model = LogisticRegression()

new_model.fit(train_x, train_y)

predicted_values_new = new_model.predict(test_x)

metrics.accuracy_score(predicted_values_new, test_y)


C:\Users\SAUMI\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [7]:
conf_metrics = metrics.confusion_matrix(predicted_values_new, test_y)

classification_report = metrics.classification_report(predicted_values_new, test_y)

print("Confusion Metrics\n")
print(conf_metrics)
print("\n\n")

print("Classfication Report\n")
print(classification_report)
print("\n\n")

Confusion Metrics

[[36  0  0  0  1  0  0  0  0  0]
 [ 0 31  0  0  0  0  1  0  1  2]
 [ 0  0 34  0  0  0  0  0  2  0]
 [ 0  0  0 38  0  1  0  0  0  0]
 [ 1  1  0  0 31  0  0  1  0  0]
 [ 0  2  0  0  0 29  0  0  0  2]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 37  0  0]
 [ 0  0  0  1  0  0  0  1 30  2]
 [ 0  0  0  1  2  2  0  1  0 33]]



Classfication Report

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        37
           1       0.91      0.89      0.90        35
           2       1.00      0.94      0.97        36
           3       0.95      0.97      0.96        39
           4       0.91      0.91      0.91        34
           5       0.91      0.88      0.89        33
           6       0.97      1.00      0.99        36
           7       0.93      1.00      0.96        37
           8       0.91      0.88      0.90        34
           9       0.85      0.85      0.85        39

    accuracy                 